---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: kommander-flux
      version: 15.0.4
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: keycloak
  valuesFrom:
    - kind: ConfigMap
      name: keycloak-15.0.4-defaults
  targetNamespace: ${releaseNamespace}
